apiVersion: v1
kind: Service
metadata:
  labels:
    app: transacao
  name: transacao
spec:
  ports:
    - name: http
      port: 2222
      protocol: TCP
      targetPort: 2222
  type: LoadBalancer
  selector:
    app: transacao